### ISSUE TITLE
iframes not working

### ISSUE THREAD

**Issue by LFSaw** [artist-network-theory-platform/vorstellen.network#2]
see eg.
https://vorstellen.network/bdf4adbb-bd6b-4859-84d6-eedce3bd4333

embeds such as e.g.

```
<iframe src="https://archive.org/embed/20160615KMA" width="640" height="480" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
```

are not working.

It'd be great to have a possibility to also include (externally hosted?) sounds and videos... 
probably the most usual platforms

+ archive.org
+ soundcloud
+ youtube
+ vimeo
+ twitch (?)

would be enough...

**Comment by dadaphl** [comment]
you can now use iframes.

**Comment by LFSaw** [comment]
hmm... can you give an example? This one https://vorstellen.network/bdf4adbb-bd6b-4859-84d6-eedce3bd4333 doesn't work, unfortunately...

**Comment by dadaphl** [comment]
strange, works on my machine. maybe delete cache?

![Screenshot from 2021-03-23 16-17-22](https://user-images.githubusercontent.com/415536/112170808-a666c980-8bf3-11eb-9223-9991b5be4f36.png)

**Comment by LFSaw** [comment]
strange... now it works :)
